const ESSENCES = ["Chêne","Hêtre","Frêne","Châtaignier","Tilleul","Peuplier","Érable sycomore","Érable champêtre","Tremble","Merisier","Érable plane","Bouleau","Charme","Douglas","Épicéa commun","Épicéa de Sitka","Sapin pectiné","Sapin de Vancouver","Pin sylvestre","Pin Laricio","Pin maritime"];
const QUALITES = ["déclassé","sec","chauffage","câblage","chablis volis","bordure"];
const DIAMETRES = Array.from({length:19},(_,i)=>20+i*5); // 20 à 110
const HAUTEURS = Array.from({length:17},(_,i)=>4+i); // 4 à 20
const SUP_HAUTEURS = [2,3,4,5,6,7,8,9,10,12];
const DEFAULT_PRICES = {superieur:300,sciage:120,tete:35};
let state = JSON.parse(localStorage.getItem('cubageV2')||'{}');
state.trees ||= []; state.settings ||= {headCoeff:1.5, prices:{}};
ESSENCES.forEach(e=>state.settings.prices[e] ||= {...DEFAULT_PRICES});
let current = {essence:null, diametre:null, hauteur:null, qualite:null, hasSup:false, supHauteur:null};
function save(){localStorage.setItem('cubageV2',JSON.stringify(state));}
function adrianII(d,h){const a=97,b=1,k=0; return Math.pow((a-b*h-k*d)/100,2)*Math.PI*d*d/40000*h;}
function adrianI(d,h){return Math.PI*d*d/40000*h;} // à remplacer si vous disposez d'une formule Adrian I spécifique
function euro(n){return (n||0).toLocaleString('fr-FR',{maximumFractionDigits:0});}
function m3(n){return (n||0).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2});}
function renderButtons(id, arr, key){const el=document.getElementById(id);el.innerHTML='';arr.forEach(v=>{const b=document.createElement('button');b.textContent=v;b.className=current[key]===v?'selected':'';b.onclick=()=>{current[key]= current[key]===v?null:v; if(key==='essence'&&v!=='Chêne'){current.hasSup=false;current.supHauteur=null;} render();};el.appendChild(b);});}
function renderQualites(){const el=document.getElementById('qualites');el.innerHTML='';QUALITES.forEach(q=>{const b=document.createElement('button');b.textContent=q;b.className=current.qualite===q?'selected':'';b.onclick=()=>{current.qualite=current.qualite===q?null:q;render();};el.appendChild(b);});}
function calcCurrent(){if(!current.essence||!current.diametre||!current.hauteur)return null; let sup=0, sciage=0; if(current.essence==='Chêne'&&current.hasSup&&current.supHauteur){const hs=Math.min(current.supHauteur,current.hauteur);sup=adrianI(current.diametre,hs);sciage=adrianII(current.diametre,Math.max(0,current.hauteur-hs));}else{sciage=adrianII(current.diametre,current.hauteur);} return {sup,sciage,totalBO:sup+sciage};}
function renderPreview(){const p=document.getElementById('preview'); const c=calcCurrent(); if(!c){p.textContent='Sélectionnez une essence, un diamètre et une hauteur.';return;} p.innerHTML=`<div>Qualité supérieure : <strong>${m3(c.sup)} m³</strong></div><div>Sciage courant : <strong>${m3(c.sciage)} m³</strong></div><div>Total bois d’œuvre : <strong>${m3(c.totalBO)} m³</strong></div><p class="muted">La tête est calculée uniquement en synthèse finale par essence.</p>`;}
function addTree(){const c=calcCurrent(); if(!c)return alert('Essence, diamètre et hauteur sont nécessaires.'); state.chantier=document.getElementById('chantier').value; state.trees.push({...current, ...c, date:new Date().toISOString()}); save(); current.diametre=null; current.hauteur=null; current.hasSup=false; current.supHauteur=null; render();}
function renderLast(){const el=document.getElementById('lastTrees'); const last=state.trees.slice(-6).reverse(); el.innerHTML=last.map(t=>`<div class="tree"><span>${t.essence} ${t.diametre} cm × ${t.hauteur} m ${t.qualite?'— '+t.qualite:''}</span><strong>${m3(t.totalBO)} m³</strong></div>`).join('')||'<p class="muted">Aucun arbre saisi.</p>';}
function grouped(){const g={}; state.trees.forEach(t=>{g[t.essence] ||= {nb:0,sup:0,sciage:0,totalBO:0}; g[t.essence].nb++; g[t.essence].sup+=t.sup; g[t.essence].sciage+=t.sciage; g[t.essence].totalBO+=t.totalBO;}); return g;}
function renderSummary(){const g=grouped(); let totalVal=0; let rows=Object.entries(g).map(([e,v])=>{const pr=state.settings.prices[e]; const tete=v.totalBO*state.settings.headCoeff; const val=v.sup*pr.superieur+v.sciage*pr.sciage+tete*pr.tete; totalVal+=val; return `<tr><td>${e}</td><td>${v.nb}</td><td>${m3(v.sup)}</td><td>${m3(v.sciage)}</td><td>${m3(v.totalBO)}</td><td>${m3(tete)}</td><td>${euro(val)} €</td></tr>`}).join(''); document.getElementById('summary').innerHTML=`<p><strong>Chantier :</strong> ${state.chantier||''}</p><table><thead><tr><th>Essence</th><th>Nb</th><th>Sup.</th><th>Sciage</th><th>Total BO</th><th>Tête</th><th>Valeur</th></tr></thead><tbody>${rows}</tbody></table><h2>Total estimatif : ${euro(totalVal)} €</h2>`;}
function renderPrices(){document.getElementById('headCoeff').value=state.settings.headCoeff; const el=document.getElementById('prices'); el.innerHTML=''; ESSENCES.forEach(e=>{const p=state.settings.prices[e]; const row=document.createElement('div'); row.className='price-row'; row.innerHTML=`<span>${e}</span><input data-e="${e}" data-k="superieur" type="number" value="${p.superieur}"><input data-e="${e}" data-k="sciage" type="number" value="${p.sciage}"><input data-e="${e}" data-k="tete" type="number" value="${p.tete}">`; el.appendChild(row);}); el.insertAdjacentHTML('afterbegin','<div class="price-row"><span>Essence</span><span>Supérieur</span><span>Sciage</span><span>Tête</span></div>');}
function saveSettings(){state.settings.headCoeff=parseFloat(document.getElementById('headCoeff').value)||1.5; document.querySelectorAll('#prices input').forEach(i=>{state.settings.prices[i.dataset.e][i.dataset.k]=parseFloat(i.value)||0;}); save(); alert('Paramètres enregistrés.'); render();}
function exportCsv(){let lines=['Chantier;Essence;Diametre;Hauteur;Qualite;Sup_m3;Sciage_m3;Total_BO_m3']; state.trees.forEach(t=>lines.push(`${state.chantier||''};${t.essence};${t.diametre};${t.hauteur};${t.qualite||'sain'};${t.sup.toFixed(3)};${t.sciage.toFixed(3)};${t.totalBO.toFixed(3)}`)); const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='cubage-bois.csv'; a.click();}
function render(){document.getElementById('chantier').value=state.chantier||''; renderButtons('essences',ESSENCES,'essence'); renderButtons('diametres',DIAMETRES,'diametre'); renderButtons('hauteurs',HAUTEURS,'hauteur'); renderButtons('supHauteurs',SUP_HAUTEURS,'supHauteur'); renderQualites(); document.getElementById('diametreValue').textContent=current.diametre||'—'; document.getElementById('hauteurValue').textContent=current.hauteur||'—'; document.getElementById('supHauteurValue').textContent=current.supHauteur||'—'; document.getElementById('cheneSupCard').style.display=current.essence==='Chêne'?'block':'none'; document.getElementById('hasSup').checked=current.hasSup; document.getElementById('supOptions').className=current.hasSup?'':'hidden'; renderPreview(); renderLast(); renderSummary(); renderPrices();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active')); b.classList.add('active'); document.getElementById(b.dataset.tab).classList.add('active'); render();});
document.getElementById('hasSup').onchange=e=>{current.hasSup=e.target.checked;render();};
document.getElementById('addTree').onclick=addTree; document.getElementById('chantier').onchange=e=>{state.chantier=e.target.value;save();}; document.getElementById('exportCsv').onclick=exportCsv; document.getElementById('printPdf').onclick=()=>window.print(); document.getElementById('saveSettings').onclick=saveSettings; document.getElementById('clearAll').onclick=()=>{if(confirm('Effacer tous les arbres saisis ?')){state.trees=[];save();render();}};
if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js');}
render();
